### ISSUE TITLE
In windows anaconda  An error occurs when the sim_outs = sim_loop.unroll(scenes_to_unroll) statement is executed in SimNet   ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by huangjieAAA** [woven-planet/l5kit#391]
D:\Anaconda3\envs\IDS\python.exe D:/l5kit-master/examples/simulation/simulation_test.py
D:\Anaconda3\envs\IDS\lib\site-packages\torch\serialization.py:604: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  " silence this warning)", UserWarning)
D:\l5kit-master\l5kit\data\zarr_dataset.py:213: RuntimeWarning: zarr dataset path should end with .zarr (for now). Open will fail for this dataset!
  dataset = ChunkedDataset("")
D:\l5kit-master\l5kit\simulation\utils.py:107: RuntimeWarning: zarr dataset path should end with .zarr (for now). Open will fail for this dataset!
  new_dataset = ChunkedDataset("")
Traceback (most recent call last):
  File "D:/l5kit-master/examples/simulation/simulation_test.py", line 59, in <module>
    sim_outs = sim_loop.unroll(scenes_to_unroll)
  File "D:\l5kit-master\l5kit\simulation\unroll.py", line 180, in unroll
    sim_dataset = SimulationDataset.from_dataset_indices(self.dataset, scene_indices, self.sim_cfg)
  File "D:\l5kit-master\l5kit\simulation\dataset.py", line 111, in from_dataset_indices
    return SimulationDataset(scene_dataset_batch, sim_cfg)
  File "D:\l5kit-master\l5kit\simulation\dataset.py", line 88, in __init__
    self.recorded_scene_dataset_batch = deepcopy(self.scene_dataset_batch)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda3\envs\IDS\lib\copy.py", line 159, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
ReferenceError: weakly-referenced object no longer exists

**Comment by MXD6** [comment]
I have the same problem.

Ubuntu 18.04.

Please, how did you solve it?

**Comment by SeasonedLeo** [comment]
did you solve this, I have the same probolem , tried solution from #400  but doesnot seem to work . Please share your solution if you have figured this out ,
