### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by MXD6** [woven-planet/l5kit#393]
Ubuntu 18.04
Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
conda 4.12.0
Python 3.9.12
l5kit 1.5.0

```
Traceback (most recent call last):
  File "/home/nio/code/l5kit-mxd/examples/simulation/simulation_test.py", line 67, in <module>
    sim_outs = sim_loop.unroll(scenes_to_unroll)  # TODO weakly-referenced object no longer exists
  File "/home/nio/anaconda3/lib/python3.9/site-packages/l5kit/simulation/unroll.py", line 180, in unroll
    sim_dataset = SimulationDataset.from_dataset_indices(self.dataset, scene_indices, self.sim_cfg)
  File "/home/nio/anaconda3/lib/python3.9/site-packages/l5kit/simulation/dataset.py", line 111, in from_dataset_indices
    return SimulationDataset(scene_dataset_batch, sim_cfg)
  File "/home/nio/anaconda3/lib/python3.9/site-packages/l5kit/simulation/dataset.py", line 88, in __init__
    self.recorded_scene_dataset_batch = deepcopy(self.scene_dataset_batch)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/nio/anaconda3/lib/python3.9/copy.py", line 151, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
ReferenceError: weakly-referenced object no longer exists
```

**Comment by kargarisaac** [comment]
@MXD6 
did you solve the problem? I get the same error on mac m1.
